POST http://localhost:8000/auth
Content-Type: application/json

{
  "username": "user_one",
  "password": "password123"
}
###

POST http://localhost:8000/auth/register
Content-Type: application/json

{
  "username": "user_one",
  "password": "password123",
  "role": "customer"
}

###
GET http://localhost:8000/users
Authorization: JWT eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI1OTY2Y2Q4OGI5MmY4MDE0YjA3MmY1NGUifQ.LqHIgl6WqwkGovlXYoah87pa7ueGMiCg65aVhIQxNr4