GET http://localhost:8000/customers

###
GET http://localhost:8000/customers/595dc4f80bbf8f3a514fc737

###
POST http://localhost:8000/customers
Content-Type: application/json

{
  "businessName": "Test for Craig ",
  "address": "Hello World"
}

###

PUT http://localhost:8000/customers/595eef01c3d7ff4d0234de1a
Content-Type: application/json

{
  "address": "Tango SUCKER"
}

###
DELETE http://localhost:8000/customers/595eef01c3d7ff4d0234de1a