GET http://localhost:8000/jobs

###

GET http://localhost:8000/jobs/595c72822cddd425680684f3

### 
POST http://localhost:8000/jobs
Content-Type: application/json

{
  "jobNumber": "TESTFORJOBS",
  "pickupStreet": "456 coke lane",
  "pickupSuburb": "Melbourne",
  "pickupPostcode": 3000,
  "pickupDate": "22/08/2017",
  "pickupState": "Vic",
  "pickupInstructions": "Hello",
  "deliveryStreet": "120 Spencer Street",
  "deliverySuburb": "Melbourne", 
  "deliveryPostcode": 3000,
  "deliveryState": "VIC", 
  "deliveryTime": "12:00",
  "deliveryDate": "23/08/2017",
  "deliveryInstructions": "Call Greg On 04786456329 to arrange gate to be opened",
  "descriptionOfGoods": "Three Kitchens", 
  "deliveryType": "Heavy Rigid",
    "driverId": 2,  
  "businessId": 89, 
  "status": "Awaiting Pick-Up",
  "dimensions": 400
}


###

PUT http://localhost:8000/jobs/595eeda0d7304e4c7dac14c4
Content-Type: application/json

{
  "deliveryAddress": "321 fake street"
}

###

DELETE http://localhost:8000/jobs/595eeda0d7304e4c7dac14c4