GET http://localhost:8000/users

###
GET http://localhost:8000/users/595dcaa732032b3bc37d0e60

###
POST http://localhost:8000/users
Content-Type: application/json

{
  "username": "boxfox",
  "password": "password"
}

###


PUT http://localhost:8000/users/595f1fdb0561e9521daa00db
Content-Type: application/json

{
  "password": "Test for update"
}

###

DELETE http://localhost:8000/users/595ee7a473484a4921f55940